webpack:
  image: node:6
  stage: build
  script:
    - cd timelinewiki_frontend
    - npm install --progress false
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
    - timelinewiki_frontend/dist