frontend:
  # Webpack build
  image: node:6
  stage: build
  script:
    - cd timelinewiki_frontend
    - npm install --progress false
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
    - timelinewiki_frontend/dist

backend:
  stage: build
  script: echo Backend
  artifacts:
    expire_in: 1 week
    paths:
    - backend

production:
  type: deploy